### PR TITLE
supporting cc, bcc, from and categories fields are optional. 

### PR DESCRIPTION
**Pull request by sachin-maheshwari**
payload would be like - 

{
"topic": "email.project.created",
"originator": "tc-notifications",
"timestamp": "2018-04-06T00:00:00",
"mime-type": "application/json",
"payload": {
   "data": {
      "subject": "3001032",
      "name": "sachin m"
   },
   "recipients" : ["tc@mailinator.com"],
   "from" : "tc@topcoder.com",
   "categories" : ["a", "b"],
   "cc" : ["cc@topcoder.com"],
   "bcc": ["bcc@topcoder.com"]
}
}

### CODE REVIEW

**Comment by vikasrohit** [comment]
@sachin-maheshwari Can we support detailed form for `from` , `ReplyTo` and `cc` fields as suggested in https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#flexible-email-address-fields?

**Comment by sachin-maheshwari** [comment]
You mean following ?  
 //Email address with name
  to: 'Some One <someone@example.org>'

That is default support as I tried...

**Comment by vikasrohit** [comment]
No, I meant

```javascript
//Object with name/email
  to: {
    name: 'Some One',
    email: 'someone@example.org',
  },
```

**Comment by sachin-maheshwari** [comment]
That is also supported you can try this.

**Comment by vikasrohit** [comment]
Awesome. I would try. Merging your PR to get changes in dev.

**Pull request merged**
